import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.core.config import settings
from app.db.base import Base
from app import models  # noqa: F401

config = context.config
config.set_main_option("sqlalchemy.url", settings.database_url)
if config.config_file_name is not None:
    fileConfig(config.config_file_name)
target_metadata = Base.metadata

# These relations are evidence retained by 0048/0049.  They are deliberately
# outside the active ORM and must never result in an autogenerated DROP.
ARCHIVE_TABLES = frozenset(
    {
        "legacy_actuator_feedback_bindings",
        "legacy_actuator_model_feedback_definitions",
        "legacy_alert_rule_evaluator_classifications",
        "legacy_device_template_classifications",
        "legacy_sensor_classifications",
    }
)

# 0046 renamed the physical project authority to aquaponics_systems while
# preserving existing index/constraint names. Each pair below was checked to
# have identical relation, columns, ordering, uniqueness and predicate.
COMPATIBILITY_NAMES = frozenset(
    {
        "ix_alert_rule_project_overrides_project_id",
        "ix_alert_rule_project_overrides_aquaponics_system_id",
        "uq_alert_rule_project_overrides_rule_scope",
        "uq_alert_rule_system_overrides_rule_scope",
        "ix_projects_code",
        "ix_aquaponics_systems_code",
        "ix_projects_disabled_by_user_id",
        "ix_aquaponics_systems_disabled_by_user_id",
        "ix_projects_is_deleted",
        "ix_aquaponics_systems_is_deleted",
        "ix_projects_owner_user_id",
        "ix_aquaponics_systems_owner_user_id",
        "ix_projects_status",
        "ix_aquaponics_systems_status",
        "ix_audit_logs_project_id_created_at",
        "ix_audit_logs_aquaponics_system_id_created_at",
        "ix_devices_project_id",
        "ix_devices_aquaponics_system_id",
        "ix_notification_outbox_project_id",
        "ix_notification_outbox_aquaponics_system_id",
        "ix_operational_incidents_project_status",
        "ix_operational_incidents_aquaponics_system_status",
        "ix_project_members_project_id",
        "ix_project_members_aquaponics_system_id",
        "uq_project_members_project_user",
        "uq_aquaponics_system_members_system_user",
        "ix_project_notification_recipients_project_id",
        "ix_project_notification_recipients_aquaponics_system_id",
        "uq_project_notification_recipient_chat",
        "uq_aquaponics_system_notification_recipient_chat",
        "ix_project_notification_risk_policies_project_id",
        "ix_project_notification_risk_policies_aquaponics_system_id",
        "uq_project_notification_risk_policy",
        "uq_aquaponics_system_notification_risk_policy",
        "ix_project_notification_settings_project_id",
        "ix_project_notification_settings_aquaponics_system_id",
        "uq_project_notification_settings_project_id",
        "uq_aquaponics_system_notification_settings_system_id",
        "ix_project_public_settings_project_id",
        "ix_project_public_settings_aquaponics_system_id",
        "uq_project_public_settings_project_id",
        "uq_aquaponics_system_public_settings_system_id",
    }
)


def include_object(object_: object, name: str | None, type_: str, reflected: bool, compare_to: object | None) -> bool:
    """Exclude only archived relations and verified compatibility names."""
    if type_ == "table" and reflected and name in ARCHIVE_TABLES:
        return False
    if type_ in {"index", "unique_constraint"} and name in COMPATIBILITY_NAMES:
        return False
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_async_migrations())
