"""v1 baseline

Revision ID: v1
Revises:
Create Date: 2026-09-22 10:17:00.512403
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'v1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuator_models',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('default_state', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('nominal_voltage_v', sa.Float(), nullable=True),
    sa.Column('voltage_tolerance_v', sa.Float(), nullable=True),
    sa.Column('zero_voltage_max_v', sa.Float(), nullable=True),
    sa.Column('minimum_running_current_a', sa.Float(), nullable=True),
    sa.Column('maximum_running_current_a', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(nominal_voltage_v IS NULL OR nominal_voltage_v > 0) AND (voltage_tolerance_v IS NULL OR voltage_tolerance_v >= 0) AND (zero_voltage_max_v IS NULL OR zero_voltage_max_v >= 0) AND (minimum_running_current_a IS NULL OR minimum_running_current_a >= 0) AND (maximum_running_current_a IS NULL OR maximum_running_current_a >= 0) AND (minimum_running_current_a IS NULL OR maximum_running_current_a IS NULL OR minimum_running_current_a <= maximum_running_current_a)', name=op.f('ck_actuator_models_electrical_values_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actuator_models')),
    sa.UniqueConstraint('code', name='uq_actuator_models_code')
    )
    op.create_index(op.f('ix_actuator_models_is_deleted'), 'actuator_models', ['is_deleted'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('evaluator_type', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evaluator_type IN ('THRESHOLD','THRESHOLD_BANDS','RANGE_BANDS','DIGITAL_STATE','THRESHOLD_DURATION','BASELINE_DEVIATION','WINDOW_DURATION','TREND','MULTI_CONDITION')", name=op.f('ck_alert_rules_alert_rule_evaluator_type_allowed')),
    sa.CheckConstraint("target_type IN ('SENSOR','ACTUATOR')", name=op.f('ck_alert_rules_alert_rule_target_type_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules')),
    sa.UniqueConstraint('code', name=op.f('uq_alert_rules_code'))
    )
    op.create_index(op.f('ix_alert_rules_public_id'), 'alert_rules', ['public_id'], unique=True)
    op.create_table('auth_rate_limit_buckets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('bucket_type', sa.String(length=40), nullable=False),
    sa.Column('bucket_key_hash', sa.String(length=64), nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("bucket_type IN ('LOGIN_IDENTITY_IP','LOGIN_IP')", name=op.f('ck_auth_rate_limit_buckets_auth_rate_limit_bucket_type_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_rate_limit_buckets')),
    sa.UniqueConstraint('bucket_type', 'bucket_key_hash', name='uq_auth_rate_limit_bucket')
    )
    op.create_index('ix_auth_rate_limit_blocked_updated', 'auth_rate_limit_buckets', ['blocked_until', 'updated_at'], unique=False)
    op.create_table('device_templates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('nominal_output_voltage_v', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('nominal_output_voltage_v IS NULL OR nominal_output_voltage_v > 0', name=op.f('ck_device_templates_nominal_voltage_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_templates')),
    sa.UniqueConstraint('code', name='uq_device_templates_code')
    )
    op.create_index('ix_device_templates_code', 'device_templates', ['code'], unique=False)
    op.create_index(op.f('ix_device_templates_is_deleted'), 'device_templates', ['is_deleted'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('resource', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('sensor_models',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('value_type', sa.String(length=30), nullable=False),
    sa.Column('chart_type', sa.String(length=30), nullable=False),
    sa.Column('measurement_semantics', sa.String(length=20), server_default='GAUGE', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_lower_threshold', sa.Float(), nullable=True),
    sa.Column('default_upper_threshold', sa.Float(), nullable=True),
    sa.Column('default_warning_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_below_threshold_message', sa.Text(), nullable=True),
    sa.Column('default_above_threshold_message', sa.Text(), nullable=True),
    sa.Column('default_alert_risk_level', sa.String(length=30), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("measurement_semantics IN ('GAUGE', 'COUNTER')", name=op.f('ck_sensor_models_measurement_semantics_allowed')),
    sa.CheckConstraint('default_lower_threshold IS NULL OR default_upper_threshold IS NULL OR default_lower_threshold < default_upper_threshold', name=op.f('ck_sensor_models_default_threshold_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_models'))
    )
    op.create_index(op.f('ix_sensor_models_code'), 'sensor_models', ['code'], unique=True)
    op.create_index(op.f('ix_sensor_models_is_deleted'), 'sensor_models', ['is_deleted'], unique=False)
    op.create_table('alert_rule_actuator_models',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('actuator_model_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actuator_model_id'], ['actuator_models.id'], name=op.f('fk_alert_rule_actuator_models_actuator_model_id_actuator_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alert_rule_actuator_models_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'actuator_model_id', name=op.f('pk_alert_rule_actuator_models'))
    )
    op.create_index(op.f('ix_alert_rule_actuator_models_actuator_model_id'), 'alert_rule_actuator_models', ['actuator_model_id'], unique=False)
    op.create_table('alert_rule_profiles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alert_rule_profiles_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rule_profiles')),
    sa.UniqueConstraint('code', name=op.f('uq_alert_rule_profiles_code'))
    )
    op.create_index(op.f('ix_alert_rule_profiles_rule_id'), 'alert_rule_profiles', ['rule_id'], unique=False)
    op.create_table('alert_rule_sensor_models',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_model_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alert_rule_sensor_models_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_model_id'], ['sensor_models.id'], name=op.f('fk_alert_rule_sensor_models_sensor_model_id_sensor_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'sensor_model_id', name=op.f('pk_alert_rule_sensor_models'))
    )
    op.create_index(op.f('ix_alert_rule_sensor_models_sensor_model_id'), 'alert_rule_sensor_models', ['sensor_model_id'], unique=False)
    op.create_table('device_template_sensors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('device_template_id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_model_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('default_location', sa.String(length=255), nullable=True),
    sa.Column('default_lower_threshold', sa.Float(), nullable=True),
    sa.Column('default_upper_threshold', sa.Float(), nullable=True),
    sa.Column('default_warning_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_below_threshold_message', sa.Text(), nullable=True),
    sa.Column('default_above_threshold_message', sa.Text(), nullable=True),
    sa.Column('default_below_risk_level', sa.String(length=30), nullable=True),
    sa.Column('default_above_risk_level', sa.String(length=30), nullable=True),
    sa.Column('default_alert_risk_level', sa.String(length=30), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_template_id'], ['device_templates.id'], name=op.f('fk_device_template_sensors_device_template_id_device_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_model_id'], ['sensor_models.id'], name=op.f('fk_device_template_sensors_sensor_model_id_sensor_models'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_template_sensors')),
    sa.UniqueConstraint('device_template_id', 'code', name='uq_device_template_sensor_code')
    )
    op.create_index(op.f('ix_device_template_sensors_device_template_id'), 'device_template_sensors', ['device_template_id'], unique=False)
    op.create_index(op.f('ix_device_template_sensors_sensor_model_id'), 'device_template_sensors', ['sensor_model_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('scenario_catalogs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('device_template_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_template_id'], ['device_templates.id'], name=op.f('fk_scenario_catalogs_device_template_id_device_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_catalogs'))
    )
    op.create_index(op.f('ix_scenario_catalogs_code'), 'scenario_catalogs', ['code'], unique=True)
    op.create_index(op.f('ix_scenario_catalogs_device_template_id'), 'scenario_catalogs', ['device_template_id'], unique=False)
    op.create_index(op.f('ix_scenario_catalogs_is_deleted'), 'scenario_catalogs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_scenario_catalogs_public_id'), 'scenario_catalogs', ['public_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('system_role', sa.Enum('ADMIN', 'OWNER', 'VIEWER', name='user_system_role'), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'LOCKED', 'SOFT_DELETED', name='user_status'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('locked_reason', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['disabled_by_user_id'], ['users.id'], name=op.f('fk_users_disabled_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['users.id'], name=op.f('fk_users_locked_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alert_rule_actuator_model_profiles',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('actuator_model_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actuator_model_id'], ['actuator_models.id'], name=op.f('fk_alert_rule_actuator_model_profiles_actuator_model_id_actuator_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['alert_rule_profiles.id'], name=op.f('fk_alert_rule_actuator_model_profiles_profile_id_alert_rule_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'actuator_model_id', name=op.f('pk_alert_rule_actuator_model_profiles'))
    )
    op.create_table('alert_rule_revisions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('business_risk_level', sa.String(length=30), nullable=False),
    sa.Column('condition_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('condition_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('consequence', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), server_default='Business rules 2026-08-24', nullable=False),
    sa.Column('source_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_by', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("business_risk_level IN ('EXTREME','VERY_HIGH','HIGH','MEDIUM','LOW_MEDIUM','LOW')", name=op.f('ck_alert_rule_revisions_alert_revision_risk_allowed')),
    sa.CheckConstraint("status IN ('DRAFT','INCOMPLETE','VALIDATED','PUBLISHED','RETIRED')", name=op.f('ck_alert_rule_revisions_alert_revision_status_allowed')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_alert_rule_revisions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_alert_rule_revisions_published_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alert_rule_revisions_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rule_revisions')),
    sa.UniqueConstraint('rule_id', 'revision', name='uq_alert_rule_revision')
    )
    op.create_index(op.f('ix_alert_rule_revisions_rule_id'), 'alert_rule_revisions', ['rule_id'], unique=False)
    op.create_foreign_key('fk_alert_rules_current_revision_id_alert_rule_revisions', 'alert_rules', 'alert_rule_revisions', ['current_revision_id'], ['id'], ondelete='SET NULL')
    op.create_table('alert_rule_sensor_model_profiles',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_model_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['alert_rule_profiles.id'], name=op.f('fk_alert_rule_sensor_model_profiles_profile_id_alert_rule_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_model_id'], ['sensor_models.id'], name=op.f('fk_alert_rule_sensor_model_profiles_sensor_model_id_sensor_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'sensor_model_id', name=op.f('pk_alert_rule_sensor_model_profiles'))
    )
    op.create_table('aquaponics_systems',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_template_id', sa.BigInteger(), nullable=True),
    sa.Column('scenario_catalog_id', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='project_status'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_template_id'], ['device_templates.id'], name=op.f('fk_aquaponics_systems_device_template_id_device_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['disabled_by_user_id'], ['users.id'], name=op.f('fk_aquaponics_systems_disabled_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_aquaponics_systems_owner_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_catalog_id'], ['scenario_catalogs.id'], name=op.f('fk_aquaponics_systems_scenario_catalog_id_scenario_catalogs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aquaponics_systems'))
    )
    op.create_index(op.f('ix_aquaponics_systems_code'), 'aquaponics_systems', ['code'], unique=True)
    op.create_index(op.f('ix_aquaponics_systems_device_template_id'), 'aquaponics_systems', ['device_template_id'], unique=False)
    op.create_index('ix_aquaponics_systems_disabled_by_user_id', 'aquaponics_systems', ['disabled_by_user_id'], unique=False)
    op.create_index(op.f('ix_aquaponics_systems_is_deleted'), 'aquaponics_systems', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_aquaponics_systems_owner_user_id'), 'aquaponics_systems', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_aquaponics_systems_public_id'), 'aquaponics_systems', ['public_id'], unique=True)
    op.create_index(op.f('ix_aquaponics_systems_scenario_catalog_id'), 'aquaponics_systems', ['scenario_catalog_id'], unique=False)
    op.create_index('ix_aquaponics_systems_status', 'aquaponics_systems', ['status'], unique=False)
    op.create_index('uq_aquaponics_systems_one_active_owner', 'aquaponics_systems', ['owner_user_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE' AND is_deleted = false"))
    op.create_table('device_template_actuators',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('device_template_id', sa.BigInteger(), nullable=False),
    sa.Column('actuator_model_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('default_name', sa.String(length=255), nullable=True),
    sa.Column('default_location', sa.String(length=255), nullable=True),
    sa.Column('default_notes', sa.Text(), nullable=True),
    sa.Column('actuator_type', sa.String(length=40), server_default='SWITCH', nullable=False),
    sa.Column('default_state', sa.Boolean(), nullable=True),
    sa.Column('command_capability', sa.String(length=30), server_default='ON_OFF', nullable=False),
    sa.Column('monitor_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('electrical_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actuator_model_id'], ['actuator_models.id'], name=op.f('fk_device_template_actuators_actuator_model_id_actuator_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_template_id'], ['device_templates.id'], name=op.f('fk_device_template_actuators_device_template_id_device_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['electrical_profile_id'], ['alert_rule_profiles.id'], name=op.f('fk_device_template_actuators_electrical_profile_id_alert_rule_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_template_actuators')),
    sa.UniqueConstraint('device_template_id', 'code', name='uq_device_template_actuator_code')
    )
    op.create_index('ix_device_template_actuators_actuator_model_id', 'device_template_actuators', ['actuator_model_id'], unique=False)
    op.create_index(op.f('ix_device_template_actuators_electrical_profile_id'), 'device_template_actuators', ['electrical_profile_id'], unique=False)
    op.create_index('ix_device_template_actuators_template_id', 'device_template_actuators', ['device_template_id'], unique=False)
    op.create_table('scenario_catalog_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('scenario_catalog_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('resource_code', sa.String(length=80), nullable=False),
    sa.Column('sensor_model_id', sa.BigInteger(), nullable=True),
    sa.Column('actuator_model_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('branches', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_reference', sa.String(length=255), server_default='Aquaponics source documents', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(target_type = 'SENSOR' AND sensor_model_id IS NOT NULL AND actuator_model_id IS NULL) OR (target_type = 'ACTUATOR' AND actuator_model_id IS NOT NULL AND sensor_model_id IS NULL)", name=op.f('ck_scenario_catalog_items_scenario_catalog_item_target_matches_model')),
    sa.ForeignKeyConstraint(['actuator_model_id'], ['actuator_models.id'], name=op.f('fk_scenario_catalog_items_actuator_model_id_actuator_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_catalog_id'], ['scenario_catalogs.id'], name=op.f('fk_scenario_catalog_items_scenario_catalog_id_scenario_catalogs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_model_id'], ['sensor_models.id'], name=op.f('fk_scenario_catalog_items_sensor_model_id_sensor_models'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_catalog_items')),
    sa.UniqueConstraint('scenario_catalog_id', 'target_type', 'resource_code', name='uq_scenario_catalog_resource_code')
    )
    op.create_index(op.f('ix_scenario_catalog_items_actuator_model_id'), 'scenario_catalog_items', ['actuator_model_id'], unique=False)
    op.create_index('ix_scenario_catalog_items_catalog_id', 'scenario_catalog_items', ['scenario_catalog_id'], unique=False)
    op.create_index(op.f('ix_scenario_catalog_items_sensor_model_id'), 'scenario_catalog_items', ['sensor_model_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=80), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('public_id', name=op.f('uq_user_sessions_public_id')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_user_sessions_refresh_token_hash'))
    )
    op.create_index('ix_user_sessions_user_expires', 'user_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('alert_rule_project_overrides',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_alert_rule_project_overrides_aquaponics_system_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alert_rule_project_overrides_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rule_project_overrides')),
    sa.UniqueConstraint('rule_id', 'aquaponics_system_id', name='uq_alert_rule_system_overrides_rule_scope')
    )
    op.create_index(op.f('ix_alert_rule_project_overrides_aquaponics_system_id'), 'alert_rule_project_overrides', ['aquaponics_system_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_audit_logs_aquaponics_system_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_aquaponics_system_id_created_at', 'audit_logs', ['aquaponics_system_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=False),
    sa.Column('device_template_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('WAITING_CONNECTION', 'ONLINE', 'OFFLINE', 'DISABLED', name='device_status'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_devices_aquaponics_system_id_aquaponics_systems'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_template_id'], ['device_templates.id'], name=op.f('fk_devices_device_template_id_device_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['disabled_by_user_id'], ['users.id'], name=op.f('fk_devices_disabled_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_aquaponics_system_id'), 'devices', ['aquaponics_system_id'], unique=False)
    op.create_index(op.f('ix_devices_code'), 'devices', ['code'], unique=True)
    op.create_index(op.f('ix_devices_device_template_id'), 'devices', ['device_template_id'], unique=False)
    op.create_index(op.f('ix_devices_is_deleted'), 'devices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_devices_public_id'), 'devices', ['public_id'], unique=True)
    op.create_table('project_members',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='VIEWER', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_project_members_aquaponics_system_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_members_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('aquaponics_system_id', 'user_id', name='uq_aquaponics_system_members_system_user')
    )
    op.create_index(op.f('ix_project_members_aquaponics_system_id'), 'project_members', ['aquaponics_system_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('project_notification_recipients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_project_notification_recipients_aquaponics_system_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_notification_recipients')),
    sa.UniqueConstraint('aquaponics_system_id', 'telegram_chat_id', name='uq_aquaponics_system_notification_recipient_chat')
    )
    op.create_index(op.f('ix_project_notification_recipients_aquaponics_system_id'), 'project_notification_recipients', ['aquaponics_system_id'], unique=False)
    op.create_table('project_notification_settings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notify_alert_recovered', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_health_status', sa.String(length=30), nullable=True),
    sa.Column('last_health_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('last_health_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_health_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_project_notification_settings_aquaponics_system_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_notification_settings')),
    sa.UniqueConstraint('aquaponics_system_id', name='uq_aquaponics_system_notification_settings_system_id')
    )
    op.create_index(op.f('ix_project_notification_settings_aquaponics_system_id'), 'project_notification_settings', ['aquaponics_system_id'], unique=False)
    op.create_table('project_public_settings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('public_slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_project_public_settings_aquaponics_system_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_public_settings')),
    sa.UniqueConstraint('aquaponics_system_id', name='uq_aquaponics_system_public_settings_system_id'),
    sa.UniqueConstraint('public_slug', name='uq_project_public_settings_public_slug')
    )
    op.create_index(op.f('ix_project_public_settings_aquaponics_system_id'), 'project_public_settings', ['aquaponics_system_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope_type = 'GLOBAL' AND scope_id IS NULL) OR (scope_type = 'AQUAPONICS_SYSTEM' AND scope_id IS NOT NULL)", name=op.f('ck_role_assignments_role_assignment_scope')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_role_assignments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_assignments_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['aquaponics_systems.id'], name=op.f('fk_role_assignments_scope_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_role_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignments')),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name='uq_role_assignments_user_role_scope')
    )
    op.create_index(op.f('ix_role_assignments_role_id'), 'role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_scope_id'), 'role_assignments', ['scope_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_index('uq_role_assignments_global', 'role_assignments', ['user_id', 'role_id'], unique=True, postgresql_where=sa.text("scope_type = 'GLOBAL'"))
    op.create_table('scada_dashboards',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED')", name=op.f('ck_scada_dashboards_status_allowed')),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_scada_dashboards_aquaponics_system_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_scada_dashboards_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scada_dashboards'))
    )
    op.create_index('ix_scada_dashboards_project_status_version', 'scada_dashboards', ['aquaponics_system_id', 'status', 'version'], unique=False)
    op.create_table('user_permission_overrides',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.BigInteger(), nullable=True),
    sa.Column('effect', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope_type = 'GLOBAL' AND scope_id IS NULL) OR (scope_type = 'AQUAPONICS_SYSTEM' AND scope_id IS NOT NULL)", name=op.f('ck_user_permission_overrides_user_permission_override_scope')),
    sa.CheckConstraint("effect IN ('ALLOW', 'DENY')", name=op.f('ck_user_permission_overrides_user_permission_override_effect')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_user_permission_overrides_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_user_permission_overrides_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['aquaponics_systems.id'], name=op.f('fk_user_permission_overrides_scope_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permission_overrides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_permission_overrides')),
    sa.UniqueConstraint('user_id', 'permission_id', 'scope_type', 'scope_id', name='uq_user_permission_overrides_user_permission_scope')
    )
    op.create_index(op.f('ix_user_permission_overrides_permission_id'), 'user_permission_overrides', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_scope_id'), 'user_permission_overrides', ['scope_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_user_id'), 'user_permission_overrides', ['user_id'], unique=False)
    op.create_index('uq_user_permission_overrides_global', 'user_permission_overrides', ['user_id', 'permission_id'], unique=True, postgresql_where=sa.text("scope_type = 'GLOBAL'"))
    op.create_table('actuators',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('actuator_model_id', sa.BigInteger(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('desired_state', sa.Boolean(), nullable=True),
    sa.Column('reported_state', sa.Boolean(), nullable=True),
    sa.Column('last_command_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_state_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voltage_v', sa.Float(), nullable=True),
    sa.Column('current_a', sa.Float(), nullable=True),
    sa.Column('electrical_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('electrical_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('electrical_alerts_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('voltage_lower_threshold', sa.Float(), nullable=True),
    sa.Column('voltage_upper_threshold', sa.Float(), nullable=True),
    sa.Column('voltage_low_message', sa.Text(), nullable=True),
    sa.Column('voltage_high_message', sa.Text(), nullable=True),
    sa.Column('voltage_low_risk_level', sa.String(length=30), nullable=True),
    sa.Column('voltage_high_risk_level', sa.String(length=30), nullable=True),
    sa.Column('current_lower_threshold', sa.Float(), nullable=True),
    sa.Column('current_upper_threshold', sa.Float(), nullable=True),
    sa.Column('current_low_message', sa.Text(), nullable=True),
    sa.Column('current_high_message', sa.Text(), nullable=True),
    sa.Column('current_low_risk_level', sa.String(length=30), nullable=True),
    sa.Column('current_high_risk_level', sa.String(length=30), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('removed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actuator_model_id'], ['actuator_models.id'], name=op.f('fk_actuators_actuator_model_id_actuator_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_actuators_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['disabled_by_user_id'], ['users.id'], name=op.f('fk_actuators_disabled_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['removed_by_user_id'], ['users.id'], name=op.f('fk_actuators_removed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actuators')),
    sa.UniqueConstraint('device_id', 'code', name='uq_actuator_device_code')
    )
    op.create_index(op.f('ix_actuators_device_id'), 'actuators', ['device_id'], unique=False)
    op.create_index(op.f('ix_actuators_is_deleted'), 'actuators', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_actuators_public_id'), 'actuators', ['public_id'], unique=True)
    op.create_table('device_credentials',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_device_credentials_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_credentials_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_credentials'))
    )
    op.create_index('uq_active_device_credential', 'device_credentials', ['device_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('uq_device_credential_version', 'device_credentials', ['device_id', 'version'], unique=True)
    op.create_table('sensors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_model_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('installation_location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('WAITING_CONNECTION', 'ONLINE', 'OFFLINE', 'DISABLED', name='sensor_status'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning_enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_risk_level', sa.String(length=30), nullable=True),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('lower_threshold', sa.Float(), nullable=True),
    sa.Column('upper_threshold', sa.Float(), nullable=True),
    sa.Column('below_threshold_message', sa.Text(), nullable=True),
    sa.Column('above_threshold_message', sa.Text(), nullable=True),
    sa.Column('below_risk_level', sa.String(length=30), nullable=True),
    sa.Column('above_risk_level', sa.String(length=30), nullable=True),
    sa.Column('alert_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('alert_delay_seconds >= 0', name=op.f('ck_sensors_alert_delay_non_negative')),
    sa.CheckConstraint('lower_threshold IS NULL OR upper_threshold IS NULL OR lower_threshold < upper_threshold', name=op.f('ck_sensors_threshold_order')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sensors_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['disabled_by_user_id'], ['users.id'], name=op.f('fk_sensors_disabled_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_model_id'], ['sensor_models.id'], name=op.f('fk_sensors_sensor_model_id_sensor_models'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensors'))
    )
    op.create_index('ix_sensors_device_id', 'sensors', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensors_is_deleted'), 'sensors', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sensors_public_id'), 'sensors', ['public_id'], unique=True)
    op.create_index('uq_sensor_device_code', 'sensors', ['device_id', 'code'], unique=True)
    op.create_table('actuator_commands',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('actuator_id', sa.BigInteger(), nullable=False),
    sa.Column('desired_state', sa.Boolean(), nullable=False),
    sa.Column('reported_state', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_publish_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_publish_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_failure_reason', sa.String(length=120), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timed_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], name=op.f('fk_actuator_commands_actuator_id_actuators'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_actuator_commands_requested_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actuator_commands'))
    )
    op.create_index(op.f('ix_actuator_commands_actuator_id'), 'actuator_commands', ['actuator_id'], unique=False)
    op.create_index('ix_actuator_commands_status_next_publish_attempt', 'actuator_commands', ['status', 'next_publish_attempt_at'], unique=False)
    op.create_table('actuator_readings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('actuator_id', sa.BigInteger(), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=True),
    sa.Column('current_a', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(length=20), server_default='UNVALIDATED', nullable=False),
    sa.Column('legacy_source_key', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("quality IN ('VALID', 'UNVALIDATED', 'INVALID')", name=op.f('ck_actuator_readings_quality_allowed')),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], name=op.f('fk_actuator_readings_actuator_id_actuators'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actuator_readings')),
    sa.UniqueConstraint('legacy_source_key', name='uq_actuator_reading_legacy_source_key')
    )
    op.create_index(op.f('ix_actuator_readings_actuator_id'), 'actuator_readings', ['actuator_id'], unique=False)
    op.create_index('ix_actuator_readings_actuator_recorded_desc', 'actuator_readings', ['actuator_id', 'recorded_at'], unique=False)
    op.create_table('alert_rule_actuator_overrides',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('actuator_id', sa.BigInteger(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], name=op.f('fk_alert_rule_actuator_overrides_actuator_id_actuators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alert_rule_actuator_overrides_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rule_actuator_overrides')),
    sa.UniqueConstraint('rule_id', 'actuator_id', name='uq_alert_rule_actuator_overrides_rule_scope')
    )
    op.create_index(op.f('ix_alert_rule_actuator_overrides_actuator_id'), 'alert_rule_actuator_overrides', ['actuator_id'], unique=False)
    op.create_table('alert_rule_sensor_overrides',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_id', sa.BigInteger(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alert_rule_sensor_overrides_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_alert_rule_sensor_overrides_sensor_id_sensors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rule_sensor_overrides')),
    sa.UniqueConstraint('rule_id', 'sensor_id', name='uq_alert_rule_sensor_overrides_rule_scope')
    )
    op.create_index(op.f('ix_alert_rule_sensor_overrides_sensor_id'), 'alert_rule_sensor_overrides', ['sensor_id'], unique=False)
    op.create_table('operational_incidents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('rule_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('device_id', sa.BigInteger(), nullable=True),
    sa.Column('sensor_id', sa.BigInteger(), nullable=True),
    sa.Column('actuator_id', sa.BigInteger(), nullable=True),
    sa.Column('context_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('technical_severity', sa.String(length=30), nullable=False),
    sa.Column('business_risk_level_snapshot', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('trigger_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acknowledged_by', sa.BigInteger(), nullable=True),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','OPEN','ACKNOWLEDGED','NORMALIZED','RESOLVED')", name=op.f('ck_operational_incidents_operational_incident_status_allowed')),
    sa.CheckConstraint("technical_severity IN ('WARNING','CRITICAL')", name=op.f('ck_operational_incidents_operational_incident_severity_allowed')),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_operational_incidents_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], name=op.f('fk_operational_incidents_actuator_id_actuators'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_operational_incidents_aquaponics_system_id_aquaponics_systems'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_operational_incidents_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_operational_incidents_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_operational_incidents_rule_id_alert_rules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_revision_id'], ['alert_rule_revisions.id'], name=op.f('fk_operational_incidents_rule_revision_id_alert_rule_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_operational_incidents_sensor_id_sensors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_incidents'))
    )
    op.create_index('ix_operational_incidents_aquaponics_system_status', 'operational_incidents', ['aquaponics_system_id', 'status'], unique=False)
    op.create_index('ix_operational_incidents_rule_status', 'operational_incidents', ['rule_id', 'status'], unique=False)
    op.create_index('uq_active_operational_incident', 'operational_incidents', ['rule_id', 'context_key'], unique=True, postgresql_where=sa.text("status IN ('PENDING','OPEN','ACKNOWLEDGED')"))
    op.create_index('uq_active_operational_incident_project_context', 'operational_incidents', ['aquaponics_system_id', 'context_key'], unique=True, postgresql_where=sa.text("status IN ('PENDING','OPEN','ACKNOWLEDGED')"))
    op.create_table('sensor_alerts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('sensor_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_type', sa.Enum('BELOW_LOWER_THRESHOLD', 'ABOVE_UPPER_THRESHOLD', 'SENSOR_OFFLINE', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trigger_value', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.BigInteger(), nullable=True),
    sa.Column('condition_active', sa.Boolean(), nullable=False),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_sensor_alerts_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_sensor_alerts_resolved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_sensor_alerts_sensor_id_sensors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_alerts'))
    )
    op.create_index('uq_active_sensor_alert', 'sensor_alerts', ['sensor_id', 'alert_type'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'OPEN', 'ACKNOWLEDGED')"))
    op.create_table('telemetry_aggregates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('sensor_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.Enum('HOUR', 'DAY', name='aggregate_period'), nullable=False),
    sa.Column('bucket_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('min_value <= avg_value AND avg_value <= max_value', name=op.f('ck_telemetry_aggregates_aggregate_value_order')),
    sa.CheckConstraint('record_count > 0', name=op.f('ck_telemetry_aggregates_aggregate_record_count_positive')),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_telemetry_aggregates_sensor_id_sensors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_aggregates'))
    )
    op.create_index('uq_aggregate_bucket', 'telemetry_aggregates', ['sensor_id', 'period', 'bucket_time'], unique=True)
    op.create_table('telemetry_readings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('sensor_id', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_telemetry_readings_sensor_id_sensors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_readings'))
    )
    op.create_index('uq_telemetry_sensor_recorded', 'telemetry_readings', ['sensor_id', 'recorded_at'], unique=True)
    op.create_table('threshold_alert_configs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('sensor_id', sa.BigInteger(), nullable=True),
    sa.Column('actuator_id', sa.BigInteger(), nullable=True),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('lower_threshold', sa.Float(), nullable=True),
    sa.Column('upper_threshold', sa.Float(), nullable=True),
    sa.Column('below_risk_level', sa.String(length=30), nullable=True),
    sa.Column('above_risk_level', sa.String(length=30), nullable=True),
    sa.Column('below_message', sa.Text(), nullable=True),
    sa.Column('above_message', sa.Text(), nullable=True),
    sa.Column('below_consequence', sa.Text(), nullable=True),
    sa.Column('above_consequence', sa.Text(), nullable=True),
    sa.Column('below_recommended_actions', sa.Text(), nullable=True),
    sa.Column('above_recommended_actions', sa.Text(), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(sensor_id IS NOT NULL AND metric_type = 'SENSOR_VALUE') OR (actuator_id IS NOT NULL AND metric_type IN ('VOLTAGE', 'CURRENT'))", name=op.f('ck_threshold_alert_configs_metric_matches_resource')),
    sa.CheckConstraint("above_risk_level IS NULL OR above_risk_level IN ('EXTREME','VERY_HIGH','HIGH','MEDIUM','LOW_MEDIUM','LOW')", name=op.f('ck_threshold_alert_configs_above_risk_allowed')),
    sa.CheckConstraint("below_risk_level IS NULL OR below_risk_level IN ('EXTREME','VERY_HIGH','HIGH','MEDIUM','LOW_MEDIUM','LOW')", name=op.f('ck_threshold_alert_configs_below_risk_allowed')),
    sa.CheckConstraint('(sensor_id IS NOT NULL AND actuator_id IS NULL) OR (sensor_id IS NULL AND actuator_id IS NOT NULL)', name=op.f('ck_threshold_alert_configs_exactly_one_resource')),
    sa.CheckConstraint('delay_seconds >= 0', name=op.f('ck_threshold_alert_configs_delay_nonnegative')),
    sa.CheckConstraint('lower_threshold IS NULL OR upper_threshold IS NULL OR lower_threshold <= upper_threshold', name=op.f('ck_threshold_alert_configs_threshold_order')),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], name=op.f('fk_threshold_alert_configs_actuator_id_actuators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_threshold_alert_configs_sensor_id_sensors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threshold_alert_configs')),
    sa.UniqueConstraint('actuator_id', 'metric_type', name='uq_threshold_alert_config_actuator_metric'),
    sa.UniqueConstraint('sensor_id', name='uq_threshold_alert_config_sensor')
    )
    op.create_index('ix_threshold_alert_configs_actuator_metric', 'threshold_alert_configs', ['actuator_id', 'metric_type'], unique=False)
    op.create_index('ix_threshold_alert_configs_sensor', 'threshold_alert_configs', ['sensor_id'], unique=False)
    op.create_table('actuator_state_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('actuator_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('command_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], name=op.f('fk_actuator_state_history_actuator_id_actuators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['command_id'], ['actuator_commands.id'], name=op.f('fk_actuator_state_history_command_id_actuator_commands'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actuator_state_history'))
    )
    op.create_index(op.f('ix_actuator_state_history_actuator_id'), 'actuator_state_history', ['actuator_id'], unique=False)
    op.create_index('ix_actuator_state_history_actuator_recorded', 'actuator_state_history', ['actuator_id', 'recorded_at'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=True),
    sa.Column('aquaponics_system_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=30), server_default='INCIDENT', nullable=False),
    sa.Column('target_recipient_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skip_reason', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['aquaponics_system_id'], ['aquaponics_systems.id'], name=op.f('fk_notification_outbox_aquaponics_system_id_aquaponics_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['operational_incidents.id'], name=op.f('fk_notification_outbox_incident_id_operational_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_recipient_id'], ['project_notification_recipients.id'], name=op.f('fk_notification_outbox_target_recipient_id_project_notification_recipients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_outbox')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_notification_outbox_idempotency_key'))
    )
    op.create_index(op.f('ix_notification_outbox_aquaponics_system_id'), 'notification_outbox', ['aquaponics_system_id'], unique=False)
    op.create_index('ix_notification_outbox_status_available', 'notification_outbox', ['status', 'available_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_target_recipient_id'), 'notification_outbox', ['target_recipient_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('outbox_id', sa.BigInteger(), nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_reference', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_category', sa.String(length=60), nullable=True),
    sa.Column('provider_status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['operational_incidents.id'], name=op.f('fk_notification_deliveries_incident_id_operational_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outbox_id'], ['notification_outbox.id'], name=op.f('fk_notification_deliveries_outbox_id_notification_outbox'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['project_notification_recipients.id'], name=op.f('fk_notification_deliveries_recipient_id_project_notification_recipients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_notification_deliveries_idempotency_key'))
    )
    op.create_index('ix_notification_deliveries_outbox_status', 'notification_deliveries', ['outbox_id', 'status'], unique=False)
    op.create_table(
        "project_scenarios",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("aquaponics_system_id", sa.BigInteger(), nullable=False),
        sa.Column("device_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("source_scenario_catalog_id", sa.BigInteger(), nullable=True),
        sa.Column("cloned_from_scenario_id", sa.BigInteger(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aquaponics_system_id"],
            ["aquaponics_systems.id"],
            name=op.f(
                "fk_project_scenarios_aquaponics_system_id_aquaponics_systems"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_project_scenarios_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_scenario_catalog_id"],
            ["scenario_catalogs.id"],
            name=op.f(
                "fk_project_scenarios_source_scenario_catalog_id_scenario_catalogs"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cloned_from_scenario_id"],
            ["project_scenarios.id"],
            name=op.f(
                "fk_project_scenarios_cloned_from_scenario_id_project_scenarios"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_project_scenarios_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_project_scenarios_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_scenarios")),
    )
    op.create_index(
        "ix_project_scenarios_aquaponics_system_id",
        "project_scenarios",
        ["aquaponics_system_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_scenarios_device_id",
        "project_scenarios",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_scenarios_public_id"),
        "project_scenarios",
        ["public_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_project_scenarios_source_scenario_catalog_id"),
        "project_scenarios",
        ["source_scenario_catalog_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_scenarios_cloned_from_scenario_id"),
        "project_scenarios",
        ["cloned_from_scenario_id"],
        unique=False,
    )
    op.create_index(
        "uq_project_scenarios_one_active_device",
        "project_scenarios",
        ["device_id"],
        unique=True,
        postgresql_where=sa.text("is_active = true AND retired_at IS NULL"),
    )

    op.create_table(
        "project_scenario_items",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("project_scenario_id", sa.BigInteger(), nullable=False),
        sa.Column("target_type", sa.String(length=30), nullable=False),
        sa.Column("sensor_id", sa.BigInteger(), nullable=True),
        sa.Column("actuator_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "source_scenario_catalog_item_id", sa.BigInteger(), nullable=True
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(target_type='SENSOR' AND sensor_id IS NOT NULL AND actuator_id IS NULL) "
            "OR (target_type='ACTUATOR' AND actuator_id IS NOT NULL AND sensor_id IS NULL)",
            name=op.f(
                "ck_project_scenario_items_project_scenario_item_target_matches_resource"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["project_scenario_id"],
            ["project_scenarios.id"],
            name=op.f(
                "fk_project_scenario_items_project_scenario_id_project_scenarios"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.id"],
            name=op.f("fk_project_scenario_items_sensor_id_sensors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["actuator_id"],
            ["actuators.id"],
            name=op.f("fk_project_scenario_items_actuator_id_actuators"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_scenario_catalog_item_id"],
            ["scenario_catalog_items.id"],
            name=op.f(
                "fk_project_scenario_items_source_scenario_catalog_item_id_scenario_catalog_items"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_scenario_items")),
    )
    op.create_index(
        "ix_project_scenario_items_scenario_id",
        "project_scenario_items",
        ["project_scenario_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_scenario_items_public_id"),
        "project_scenario_items",
        ["public_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_project_scenario_items_sensor_id"),
        "project_scenario_items",
        ["sensor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_scenario_items_actuator_id"),
        "project_scenario_items",
        ["actuator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_scenario_items_source_scenario_catalog_item_id"),
        "project_scenario_items",
        ["source_scenario_catalog_item_id"],
        unique=False,
    )
    op.create_index(
        "uq_project_scenario_items_sensor",
        "project_scenario_items",
        ["project_scenario_id", "sensor_id"],
        unique=True,
        postgresql_where=sa.text(
            "sensor_id IS NOT NULL AND retired_at IS NULL"
        ),
    )
    op.create_index(
        "uq_project_scenario_items_actuator",
        "project_scenario_items",
        ["project_scenario_id", "actuator_id"],
        unique=True,
        postgresql_where=sa.text(
            "actuator_id IS NOT NULL AND retired_at IS NULL"
        ),
    )

    op.create_table(
        "project_scenario_branches",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("project_scenario_item_id", sa.BigInteger(), nullable=False),
        sa.Column("branch_key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("evaluator_type", sa.String(length=50), nullable=False),
        sa.Column(
            "condition_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "duration_seconds",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("business_risk_level", sa.String(length=30), nullable=False),
        sa.Column("message_template", sa.Text(), nullable=True),
        sa.Column("consequence", sa.Text(), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=True),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evaluator_type IN ("
            "'THRESHOLD','THRESHOLD_BANDS','RANGE_BANDS','DIGITAL_STATE',"
            "'THRESHOLD_DURATION','BASELINE_DEVIATION','WINDOW_DURATION',"
            "'TREND','MULTI_CONDITION')",
            name=op.f(
                "ck_project_scenario_branches_project_scenario_branch_evaluator_type_allowed"
            ),
        ),
        sa.CheckConstraint(
            "business_risk_level IN "
            "('EXTREME','VERY_HIGH','HIGH','MEDIUM','LOW_MEDIUM','LOW')",
            name=op.f(
                "ck_project_scenario_branches_project_scenario_branch_risk_allowed"
            ),
        ),
        sa.CheckConstraint(
            "duration_seconds >= 0",
            name=op.f(
                "ck_project_scenario_branches_project_scenario_branch_duration_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "position >= 0",
            name=op.f(
                "ck_project_scenario_branches_project_scenario_branch_position_nonnegative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["project_scenario_item_id"],
            ["project_scenario_items.id"],
            name=op.f(
                "fk_project_scenario_branches_project_scenario_item_id_project_scenario_items"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_project_scenario_branches_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_project_scenario_branches_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_scenario_branches")),
    )
    op.create_index(
        "ix_project_scenario_branches_item_id",
        "project_scenario_branches",
        ["project_scenario_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_scenario_branches_public_id"),
        "project_scenario_branches",
        ["public_id"],
        unique=True,
    )
    op.create_index(
        "uq_project_scenario_branches_active_key",
        "project_scenario_branches",
        ["project_scenario_item_id", "branch_key"],
        unique=True,
        postgresql_where=sa.text("retired_at IS NULL"),
    )

    op.add_column(
        "operational_incidents",
        sa.Column("project_scenario_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "operational_incidents",
        sa.Column("project_scenario_item_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "operational_incidents",
        sa.Column("project_scenario_branch_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "operational_incidents",
        sa.Column("resolution_reason", sa.String(length=50), nullable=True),
    )
    op.create_foreign_key(
        op.f(
            "fk_operational_incidents_project_scenario_id_project_scenarios"
        ),
        "operational_incidents",
        "project_scenarios",
        ["project_scenario_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f(
            "fk_operational_incidents_project_scenario_item_id_project_scenario_items"
        ),
        "operational_incidents",
        "project_scenario_items",
        ["project_scenario_item_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f(
            "fk_operational_incidents_project_scenario_branch_id_project_scenario_branches"
        ),
        "operational_incidents",
        "project_scenario_branches",
        ["project_scenario_branch_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("ix_operational_incidents_project_scenario_id"),
        "operational_incidents",
        ["project_scenario_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_incidents_project_scenario_item_id"),
        "operational_incidents",
        ["project_scenario_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_incidents_project_scenario_branch_id"),
        "operational_incidents",
        ["project_scenario_branch_id"],
        unique=False,
    )
    op.create_index(
        "uq_active_operational_incident_scenario_branch",
        "operational_incidents",
        ["project_scenario_branch_id"],
        unique=True,
        postgresql_where=sa.text(
            "project_scenario_branch_id IS NOT NULL "
            "AND status IN ('PENDING','OPEN','ACKNOWLEDGED')"
        ),
    )


    # ### end Alembic commands ###

def downgrade() -> None:
    raise RuntimeError(
        "V1 baseline downgrade is intentionally unsupported; restore from backup "
        "or recreate an explicitly disposable database."
    )
