import { useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Copy, Pencil, Plus, Trash2 } from "lucide-react"
import type { AlertScenario, AlertScenarioInput, RiskLevel } from "@/api/contracts"
import { createActuatorScenario, createSensorScenario, deleteActuatorScenario, deleteSensorScenario, listActuatorScenarios, listSensorScenarios, queryKeys, updateActuatorScenario, updateSensorScenario } from "@/api/resources"
import { errorMessage } from "@/api/client"
import { Button } from "@/shared/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/shared/ui/dialog"
import { Input } from "@/shared/ui/input"
import { Label } from "@/shared/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/ui/select"
import { Switch } from "@/shared/ui/switch"
import { Textarea } from "@/shared/ui/textarea"

type Props = { target: "SENSOR" | "ACTUATOR"; systemId: string; deviceId: string; resourceId: string; canCreate: boolean; canUpdate: boolean; canDelete: boolean }
const risks: RiskLevel[] = ["LOW", "LOW_MEDIUM", "MEDIUM", "HIGH", "VERY_HIGH", "EXTREME"]
const empty = (target: Props["target"]): AlertScenarioInput => ({ name: "", is_enabled: true, risk_level: "MEDIUM", duration_seconds: 0, ...(target === "SENSOR" ? { range_mode: "OUTSIDE_RANGE", range: { min: null, max: null } } : { reported_state: null, voltage: null, current: null }) })

export function AlertScenarioSection(props: Props) {
  const { target, systemId, deviceId, resourceId } = props
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AlertScenario | null>(null); const [draft, setDraft] = useState<AlertScenarioInput>(() => empty(target))
  const key = target === "SENSOR" ? queryKeys.sensorScenarios(systemId, deviceId, resourceId) : queryKeys.actuatorScenarios(systemId, deviceId, resourceId)
  const query = useQuery({ queryKey: key, queryFn: () => target === "SENSOR" ? listSensorScenarios(systemId, deviceId, resourceId) : listActuatorScenarios(systemId, deviceId, resourceId) })
  const refresh = () => client.invalidateQueries({ queryKey: key })
  const save = useMutation({ mutationFn: () => editing ? (target === "SENSOR" ? updateSensorScenario(systemId, deviceId, resourceId, editing.id, draft) : updateActuatorScenario(systemId, deviceId, resourceId, editing.id, draft)) : (target === "SENSOR" ? createSensorScenario(systemId, deviceId, resourceId, draft) : createActuatorScenario(systemId, deviceId, resourceId, draft)), onSuccess: async () => { await refresh(); setOpen(false) } })
  const toggle = useMutation({ mutationFn: (item: AlertScenario) => target === "SENSOR" ? updateSensorScenario(systemId, deviceId, resourceId, item.id, { is_enabled: !item.is_enabled }) : updateActuatorScenario(systemId, deviceId, resourceId, item.id, { is_enabled: !item.is_enabled }), onSuccess: refresh })
  const remove = useMutation({ mutationFn: (id: string) => target === "SENSOR" ? deleteSensorScenario(systemId, deviceId, resourceId, id) : deleteActuatorScenario(systemId, deviceId, resourceId, id), onSuccess: refresh })
  const show = (item?: AlertScenario, duplicate = false) => { setEditing(item && !duplicate ? item : null); setDraft(item ? fromScenario(item, duplicate) : empty(target)); setOpen(true) }
  return <Card><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>Kịch bản cảnh báo</CardTitle>{props.canCreate ? <Button size="sm" onClick={() => show()}><Plus />Tạo kịch bản</Button> : null}</div></CardHeader><CardContent className="space-y-3">{query.isError ? <p role="alert" className="text-sm text-destructive">{errorMessage(query.error)}</p> : query.data?.length ? query.data.map(item => <div key={item.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><p className="font-semibold">{item.name}</p><span className="rounded-full bg-muted px-2 py-0.5 text-xs">{item.risk_level}</span></div><p className="mt-1 text-sm text-muted-foreground">{summary(item)} · Duy trì {item.duration_seconds} giây</p></div><Switch aria-label={`${item.is_enabled ? "Tắt" : "Bật"} ${item.name}`} checked={item.is_enabled} disabled={!props.canUpdate || toggle.isPending} onCheckedChange={() => toggle.mutate(item)} /></div><div className="mt-3 flex flex-wrap gap-2">{props.canUpdate ? <Button size="sm" variant="outline" onClick={() => show(item)}><Pencil />Sửa</Button> : null}{props.canCreate ? <Button size="sm" variant="outline" onClick={() => show(item, true)}><Copy />Nhân bản</Button> : null}{props.canDelete ? <Button size="sm" variant="outline" onClick={() => remove.mutate(item.id)}><Trash2 />Xóa</Button> : null}</div></div>) : <p className="text-sm text-muted-foreground">Chưa có kịch bản cảnh báo.</p>}</CardContent><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing ? "Sửa kịch bản cảnh báo" : "Tạo kịch bản cảnh báo"}</DialogTitle><DialogDescription>Điều kiện được đánh giá trên dữ liệu thực tế của tài nguyên này.</DialogDescription></DialogHeader><ScenarioForm target={target} value={draft} onChange={setDraft} /><DialogFooter><Button variant="ghost" onClick={() => setOpen(false)}>Hủy</Button><Button onClick={() => save.mutate()} disabled={save.isPending || !valid(target, draft)}>{editing ? "Lưu thay đổi" : "Tạo kịch bản"}</Button></DialogFooter>{save.isError ? <p role="alert" className="text-sm text-destructive">{errorMessage(save.error)}</p> : null}</DialogContent></Dialog></Card>
}

function ScenarioForm({ target, value, onChange }: { target: Props["target"]; value: AlertScenarioInput; onChange: (value: AlertScenarioInput) => void }) {
  return <div className="space-y-4"><Field label="Tên kịch bản"><Input value={value.name} onChange={e => onChange({ ...value, name: e.target.value })} /></Field>{target === "ACTUATOR" ? <><Field label="Trạng thái cơ cấu"><Select value={value.reported_state == null ? "ANY" : value.reported_state ? "ON" : "OFF"} onValueChange={v => onChange({ ...value, reported_state: v === "ANY" ? null : v === "ON" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ON">Bật</SelectItem><SelectItem value="OFF">Tắt</SelectItem><SelectItem value="ANY">Bất kỳ</SelectItem></SelectContent></Select></Field><RangeFields label="Điện áp" unit="V" value={value.voltage} onChange={voltage => onChange({ ...value, voltage })} /><RangeFields label="Dòng điện" unit="A" value={value.current} onChange={current => onChange({ ...value, current })} /></> : <><Field label="Điều kiện cảnh báo"><Select value={value.range_mode ?? "OUTSIDE_RANGE"} onValueChange={v => onChange({ ...value, range_mode: v as "INSIDE_RANGE" | "OUTSIDE_RANGE" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="OUTSIDE_RANGE">Ngoài khoảng</SelectItem><SelectItem value="INSIDE_RANGE">Trong khoảng</SelectItem></SelectContent></Select></Field><RangeFields label="Giá trị" unit="" value={value.range} required onChange={range => onChange({ ...value, range })} /></>}<Field label="Duy trì trong (giây)"><Input type="number" min={0} step={1} value={value.duration_seconds} onChange={e => onChange({ ...value, duration_seconds: Number(e.target.value) })} /></Field><Field label="Mức độ rủi ro"><Select value={value.risk_level} onValueChange={v => onChange({ ...value, risk_level: v as RiskLevel })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{risks.map(r => <SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select></Field><Text label="Thông báo" value={value.message ?? ""} onChange={message => onChange({ ...value, message })} /><Text label="Ảnh hưởng" value={value.consequence ?? ""} onChange={consequence => onChange({ ...value, consequence })} /><Text label="Khắc phục" value={value.recommended_action ?? ""} onChange={recommended_action => onChange({ ...value, recommended_action })} /></div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label>{label}</Label><div className="mt-1">{children}</div></div> }
function RangeFields({ label, unit, value, onChange, required = false }: { label: string; unit: string; value?: { min: number | null; max: number | null } | null; onChange: (v: { min: number | null; max: number | null } | null) => void; required?: boolean }) { const set = (key: "min" | "max", raw: string) => { const next = { min: value?.min ?? null, max: value?.max ?? null, [key]: raw === "" ? null : Number(raw) }; onChange(!required && next.min == null && next.max == null ? null : next) }; return <fieldset><legend className="text-sm font-medium">{label}</legend><div className="mt-1 grid grid-cols-2 gap-3"><div><Label>Từ</Label><Input type="number" step="any" value={value?.min ?? ""} onChange={e => set("min", e.target.value)} /></div><div><Label>Đến {unit}</Label><Input type="number" step="any" value={value?.max ?? ""} onChange={e => set("max", e.target.value)} /></div></div></fieldset> }
function Text({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <Field label={label}><Textarea value={value} onChange={e => onChange(e.target.value)} /></Field> }
function valid(target: Props["target"], d: AlertScenarioInput) { const ranges = target === "SENSOR" ? [d.range] : [d.voltage, d.current]; const bad = ranges.some(r => r?.min != null && r?.max != null && r.min > r.max); return Boolean(d.name.trim()) && !bad && d.duration_seconds >= 0 && (target === "SENSOR" ? Boolean(d.range && (d.range.min != null || d.range.max != null)) : d.reported_state != null || Boolean(d.voltage) || Boolean(d.current)) }
function fromScenario(item: AlertScenario, duplicate: boolean): AlertScenarioInput { return { name: duplicate ? `${item.name} (bản sao)` : item.name, is_enabled: item.is_enabled, risk_level: item.risk_level, duration_seconds: item.duration_seconds, message: item.message, consequence: item.consequence, recommended_action: item.recommended_action, range_mode: item.condition.range_mode, range: item.condition.range, reported_state: item.condition.reported_state, voltage: item.condition.voltage, current: item.condition.current } }
function rangeText(label: string, range?: { min: number | null; max: number | null } | null) { if (!range) return null; if (range.min != null && range.max != null) return range.min === range.max ? `${label} = ${range.min}` : `${range.min} ≤ ${label} ≤ ${range.max}`; return range.min != null ? `${label} ≥ ${range.min}` : `${label} ≤ ${range.max}` }
function summary(item: AlertScenario) { if (item.target_type === "SENSOR") return `${item.condition.range_mode === "INSIDE_RANGE" ? "Trong" : "Ngoài"} khoảng ${rangeText("giá trị", item.condition.range) ?? "—"}`; return [item.condition.reported_state == null ? null : `Trạng thái ${item.condition.reported_state ? "Bật" : "Tắt"}`, rangeText("V", item.condition.voltage), rangeText("A", item.condition.current)].filter(Boolean).join(" AND ") }
