import { useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Boxes, Database, Plus } from "lucide-react"
import { createActuatorModel, createDeviceTemplate, createSensorModel, listActuatorModels, listDeviceTemplates, listSensorModels, queryKeys } from "@/api/resources"
import { useAuth } from "@/app/auth"
import { Button } from "@/shared/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/ui/card"
import { Input } from "@/shared/ui/input"
import { Label } from "@/shared/ui/label"
import { EmptyState } from "@/shared/ui/empty-state"
import { Skeleton } from "@/shared/ui/skeleton"
import { StatusBadge } from "@/shared/ui/status-badge"
import { errorMessage } from "@/api/client"

type CatalogTab = "templates" | "sensors" | "actuators"

export function CatalogsCanonicalPage() {
  const [tab, setTab] = useState<CatalogTab>("templates"); const { can } = useAuth(); const client = useQueryClient()
  const templates = useQuery({ queryKey: queryKeys.templates, queryFn: listDeviceTemplates, enabled: tab === "templates" })
  const sensors = useQuery({ queryKey: queryKeys.sensorModels, queryFn: listSensorModels, enabled: tab === "sensors" })
  const actuators = useQuery({ queryKey: queryKeys.actuatorModels, queryFn: listActuatorModels, enabled: tab === "actuators" })
  const refresh = () => { void client.invalidateQueries({ queryKey: queryKeys.templates }); void client.invalidateQueries({ queryKey: queryKeys.sensorModels }); void client.invalidateQueries({ queryKey: queryKeys.actuatorModels }) }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Danh mục vận hành</h1><p className="text-sm text-muted-foreground">DeviceTemplate, SensorModel và ActuatorModel là catalog, không phải runtime instance.</p></div><div className="flex gap-2 overflow-x-auto border-b pb-2">{([["templates", "DeviceTemplate"], ["sensors", "SensorModel"], ["actuators", "ActuatorModel"]] as const).map(([value, label]) => <Button key={value} variant={tab === value ? "default" : "outline"} size="sm" onClick={() => setTab(value)}>{label}</Button>)}</div>{tab === "templates" ? <TemplateCatalog loading={templates.isLoading} error={templates.error} items={templates.data ?? []} canCreate={can("device_templates.create")} onCreated={refresh} /> : tab === "sensors" ? <ModelCatalog title="SensorModel" loading={sensors.isLoading} error={sensors.error} items={sensors.data ?? []} canCreate={can("sensor_models.create")} onCreated={refresh} createItem={(payload) => createSensorModel({ code: payload.code, name: payload.name, unit: payload.unit })} /> : <ModelCatalog title="ActuatorModel" loading={actuators.isLoading} error={actuators.error} items={actuators.data ?? []} canCreate={can("actuator_models.create")} onCreated={refresh} createItem={(payload) => createActuatorModel({ code: payload.code, name: payload.name })} />}</div>
}

function TemplateCatalog({ loading, error, items, canCreate, onCreated }: { loading: boolean; error: unknown; items: Awaited<ReturnType<typeof listDeviceTemplates>>; canCreate: boolean; onCreated: () => void }) { const [open, setOpen] = useState(false); const [code, setCode] = useState(""); const [name, setName] = useState(""); const create = useMutation({ mutationFn: () => createDeviceTemplate({ code: code.trim().toUpperCase(), name: name.trim() }), onSuccess: () => { setCode(""); setName(""); setOpen(false); onCreated() } }); if (loading) return <Skeleton className="h-80" />; if (error) return <EmptyState icon={Boxes} title="Không thể tải DeviceTemplate" description={errorMessage(error)} />; return <div className="space-y-4">{canCreate ? <Button onClick={() => setOpen((value) => !value)}><Plus />Thêm DeviceTemplate</Button> : null}{open ? <form className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-3" onSubmit={(event) => { event.preventDefault(); create.mutate() }}><div><Label htmlFor="template-code">Code</Label><Input id="template-code" className="mt-1" value={code} onChange={(event) => setCode(event.target.value)} required /></div><div><Label htmlFor="template-name">Tên</Label><Input id="template-name" className="mt-1" value={name} onChange={(event) => setName(event.target.value)} required /></div><Button className="self-end" type="submit">Lưu</Button></form> : null}<div className="grid gap-4 md:grid-cols-2">{items.map((item) => <Card key={item.id}><CardHeader><CardTitle className="flex items-center justify-between gap-2 text-base"><span>{item.name}</span><StatusBadge value={item.is_active ? "ACTIVE" : "DISABLED"} /></CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{item.code}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-lg bg-muted p-3"><span className="text-xs text-muted-foreground">Sensor slot</span><p className="font-semibold">{item.sensors.length}</p></div><div className="rounded-lg bg-muted p-3"><span className="text-xs text-muted-foreground">Actuator slot</span><p className="font-semibold">{item.actuators.length}</p></div></div><div className="mt-4 space-y-1 text-xs text-muted-foreground">{item.sensors.map((slot) => <p key={`s-${slot.id}`}>Sensor · {slot.code} · {slot.sensor_model_name}</p>)}{item.actuators.map((slot) => <p key={`a-${slot.id}`}>Actuator · {slot.code} · {slot.actuator_model_name}</p>)}</div></CardContent></Card>)}</div>{!items.length ? <EmptyState icon={Boxes} title="Chưa có template" description="Tạo catalog template trước khi khởi tạo Device." /> : null}</div> }

function ModelCatalog({ title, loading, error, items, canCreate, onCreated, createItem }: { title: string; loading: boolean; error: unknown; items: Array<{ id: number; code: string; name: string; unit?: string; data_type?: string; is_active: boolean }>; canCreate: boolean; onCreated: () => void; createItem: (payload: { code: string; name: string; unit: string }) => Promise<unknown> }) { const [open, setOpen] = useState(false); const [code, setCode] = useState(""); const [name, setName] = useState(""); const [unit, setUnit] = useState(""); const create = useMutation({ mutationFn: () => createItem({ code: code.trim().toUpperCase(), name: name.trim(), unit: unit.trim() }), onSuccess: () => { setCode(""); setName(""); setUnit(""); setOpen(false); onCreated() } }); if (loading) return <Skeleton className="h-80" />; if (error) return <EmptyState icon={Database} title={`Không thể tải ${title}`} description={errorMessage(error)} />; return <div className="space-y-4">{canCreate ? <Button onClick={() => setOpen((value) => !value)}><Plus />Thêm {title}</Button> : null}{open ? <form className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-4" onSubmit={(event) => { event.preventDefault(); create.mutate() }}><div><Label htmlFor={`${title}-code`}>Code</Label><Input id={`${title}-code`} className="mt-1" value={code} onChange={(event) => setCode(event.target.value)} required /></div><div><Label htmlFor={`${title}-name`}>Tên</Label><Input id={`${title}-name`} className="mt-1" value={name} onChange={(event) => setName(event.target.value)} required /></div><div><Label htmlFor={`${title}-unit`}>Đơn vị</Label><Input id={`${title}-unit`} className="mt-1" value={unit} onChange={(event) => setUnit(event.target.value)} placeholder="—" /></div><Button className="self-end" type="submit">Lưu</Button></form> : null}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Card key={item.id}><CardContent className="p-5"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{item.name}</p><p className="text-sm text-muted-foreground">{item.code}</p></div><StatusBadge value={item.is_active ? "ACTIVE" : "DISABLED"} /></div><p className="mt-4 text-sm text-muted-foreground">{"unit" in item ? item.unit ?? "Chưa có đơn vị" : item.data_type ?? "Actuator model"}</p></CardContent></Card>)}</div>{!items.length ? <EmptyState icon={Database} title={`Chưa có ${title}`} description="Catalog sẽ xuất hiện tại đây khi được tạo." /> : null}</div> }
