import { useState, type FormEvent } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Link, useParams } from "react-router-dom"
import { errorMessage } from "@/api/client"
import { acknowledgeAlert, createDevice, exportMqttConfig, getAlertSettings, getMonitoringLatest, getMonitoringSeries, getScadaRuntime, getSystem, listActivities, listAlerts, listDevices, listMembers, queryKeys, resolveAlert, updateAlertSettings, updateMember } from "@/api/resources"
import type { MonitoringRange } from "@/api/contracts"
import { useAuth } from "@/app/auth"

type View = "devices" | "monitoring" | "alerts" | "members" | "activities" | "scada" | "settings"
const ranges: MonitoringRange[] = ["1h", "6h", "12h", "24h", "30d"]

export function SystemPage() {
  const { systemId: routeSystemId } = useParams(); const systemId = routeSystemId ?? ""; const queryClient = useQueryClient(); const { has } = useAuth()
  const [view, setView] = useState<View>("devices"); const [range, setRange] = useState<MonitoringRange>("24h"); const [code, setCode] = useState(""); const [name, setName] = useState("")
  const system = useQuery({ queryKey: queryKeys.system(systemId), queryFn: () => getSystem(systemId), enabled: Boolean(systemId) })
  const devices = useQuery({ queryKey: queryKeys.devices(systemId), queryFn: () => listDevices(systemId), enabled: view === "devices" })
  const latest = useQuery({ queryKey: queryKeys.monitoringLatest(systemId), queryFn: () => getMonitoringLatest(systemId), enabled: view === "monitoring" })
  const series = useQuery({ queryKey: queryKeys.monitoringSeries(systemId, range), queryFn: () => getMonitoringSeries(systemId, range), enabled: view === "monitoring" })
  const alerts = useQuery({ queryKey: queryKeys.alerts(systemId), queryFn: () => listAlerts(systemId), enabled: view === "alerts" })
  const members = useQuery({ queryKey: queryKeys.members(systemId), queryFn: () => listMembers(systemId), enabled: view === "members" })
  const activities = useQuery({ queryKey: queryKeys.activities(systemId), queryFn: () => listActivities(systemId), enabled: view === "activities" })
  const scada = useQuery({ queryKey: queryKeys.scada(systemId), queryFn: () => getScadaRuntime(systemId), enabled: view === "scada" })
  const settings = useQuery({ queryKey: queryKeys.alertSettings(systemId), queryFn: () => getAlertSettings(systemId), enabled: view === "settings" })
  const creation = useMutation({ mutationFn: () => createDevice(systemId, { code: code.trim().toUpperCase(), name: name.trim() }), onSuccess: async () => { setCode(""); setName(""); await queryClient.invalidateQueries({ queryKey: queryKeys.devices(systemId) }) } })
  const alertChange = useMutation({ mutationFn: ({ id, action }: { id: number; action: "acknowledge" | "resolve" }) => action === "acknowledge" ? acknowledgeAlert(systemId, id) : resolveAlert(systemId, id, { resolution_note: "Đã xử lý từ giao diện" }), onSuccess: async () => queryClient.invalidateQueries({ queryKey: queryKeys.alerts(systemId) }) })
  const memberChange = useMutation({ mutationFn: ({ userId, role }: { userId: string; role: "VIEWER" | "TECHNICIAN" | "OWNER" }) => updateMember(systemId, userId, { role }), onSuccess: async () => queryClient.invalidateQueries({ queryKey: queryKeys.members(systemId) }) })
  const saveSettings = useMutation({ mutationFn: (payload: { enabled?: boolean; in_app_enabled?: boolean; telegram_enabled?: boolean }) => updateAlertSettings(systemId, payload), onSuccess: async () => queryClient.invalidateQueries({ queryKey: queryKeys.alertSettings(systemId) }) })
  const downloadMqtt = async () => { const payload = await exportMqttConfig(systemId); const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${system.data?.code || "aquaponics"}-mqtt-config.json`; anchor.click(); URL.revokeObjectURL(url) }
  const submit = (event: FormEvent) => { event.preventDefault(); creation.mutate() }
  if (system.isLoading) return <p>Đang tải…</p>
  if (!system.data) return <p className="text-destructive">{errorMessage(system.error)}</p>
  const tabs: { key: View; label: string; permission: string }[] = [{ key: "devices", label: "Device", permission: "devices.read" }, { key: "monitoring", label: "Giám sát", permission: "monitoring.read" }, { key: "alerts", label: "Alert", permission: "incidents.read" }, { key: "members", label: "Member", permission: "aquaponics_systems.read" }, { key: "activities", label: "Hoạt động", permission: "aquaponics_systems.read" }, { key: "scada", label: "Sơ đồ vận hành", permission: "scada.read" }, { key: "settings", label: "Thiết lập Alert", permission: "incidents.read" }]
  return <section className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link className="text-sm text-primary" to="/aquaponics-systems">← Hệ thống Aquaponics</Link><h1 className="text-3xl font-bold">{system.data.name}</h1><p className="text-muted-foreground">{system.data.code} · {system.data.location || "Chưa đặt vị trí"}</p></div>{has("mqtt_config.export") && <button className="rounded border px-3 py-2" onClick={() => void downloadMqtt()}>Xuất cấu hình MQTT</button>}</div><nav className="flex flex-wrap gap-2 border-b pb-3">{tabs.filter((tab) => has(tab.permission)).map((tab) => <button key={tab.key} className={`rounded px-3 py-2 ${view === tab.key ? "bg-primary text-primary-foreground" : "bg-muted"}`} onClick={() => setView(tab.key)}>{tab.label}</button>)}</nav>
    {view === "devices" && <div className="space-y-4">{has("devices.create") && <form className="flex flex-wrap gap-2 rounded border p-3" onSubmit={submit}><input className="rounded border bg-background p-2" placeholder="Mã Device" value={code} onChange={(event) => setCode(event.target.value)} required /><input className="rounded border bg-background p-2" placeholder="Tên Device" value={name} onChange={(event) => setName(event.target.value)} required /><button className="rounded bg-primary px-4 text-primary-foreground">Thêm Device</button></form>}<div className="grid gap-3 md:grid-cols-2">{devices.data?.map((device) => <Link className="rounded-xl border bg-card p-4 hover:border-primary" key={device.id} to={`/aquaponics-systems/${systemId}/devices/${device.id}`}><div className="flex justify-between"><strong>{device.name}</strong><span className="text-xs">{device.status}</span></div><p className="text-sm text-muted-foreground">{device.code}</p><p className="mt-3 text-sm">{device.sensors.length} Sensor · {device.actuators.length} Actuator</p></Link>)}</div></div>}
    {view === "monitoring" && <div className="space-y-4"><div className="flex flex-wrap gap-2">{ranges.map((item) => <button className={`rounded border px-3 py-1 ${range === item ? "bg-primary text-primary-foreground" : ""}`} key={item} onClick={() => setRange(item)}>{item}</button>)}</div><DataPanel data={{ latest: latest.data, series: series.data }} error={latest.error || series.error} /></div>}
    {view === "alerts" && <div className="space-y-3">{alerts.data?.map((alert) => <article key={alert.id} className="rounded border bg-card p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{alert.resource_type} · {alert.severity} · {alert.status}</strong><p>{alert.message}</p><small>{new Date(alert.started_at).toLocaleString("vi-VN")} · {alert.metric}</small></div><div className="flex gap-2">{alert.status === "OPEN" && has("incidents.acknowledge") && <button className="rounded border px-3" onClick={() => alertChange.mutate({ id: alert.id, action: "acknowledge" })}>Xác nhận</button>}{alert.status !== "RESOLVED" && has("incidents.resolve") && <button className="rounded bg-primary px-3 text-primary-foreground" onClick={() => alertChange.mutate({ id: alert.id, action: "resolve" })}>Xử lý</button>}</div></div></article>)}{alerts.data?.length === 0 && <p>Không có Alert.</p>}</div>}
    {view === "members" && <div className="space-y-2">{members.data?.map((member) => <div className="flex flex-wrap items-center justify-between gap-2 rounded border p-3" key={member.id}><span>{member.name} · {member.role} · {new Date(member.joined_at).toLocaleDateString("vi-VN")}</span>{has("aquaponics_systems.manage_members") && <select className="rounded border bg-background p-1" value={member.role} onChange={(event) => memberChange.mutate({ userId: member.user_id, role: event.target.value as "VIEWER" | "TECHNICIAN" | "OWNER" })}><option value="VIEWER">VIEWER</option><option value="TECHNICIAN">TECHNICIAN</option><option value="OWNER">OWNER</option></select>}</div>)}</div>}
    {view === "activities" && <DataPanel data={activities.data} error={activities.error} />}
    {view === "scada" && <DataPanel data={scada.data} error={scada.error} />}
    {view === "settings" && settings.data && <div className="max-w-xl space-y-3 rounded border bg-card p-4"><label className="flex items-center justify-between">Alert evaluation enabled <input type="checkbox" checked={settings.data.enabled} onChange={(event) => saveSettings.mutate({ enabled: event.target.checked })} /></label><label className="flex items-center justify-between">In-app delivery <input type="checkbox" checked={settings.data.in_app_enabled} onChange={(event) => saveSettings.mutate({ in_app_enabled: event.target.checked })} /></label><label className="flex items-center justify-between">Telegram delivery <input type="checkbox" checked={settings.data.telegram_enabled} onChange={(event) => saveSettings.mutate({ telegram_enabled: event.target.checked })} /></label></div>}
  </section>
}

function DataPanel({ data, error }: { data: unknown; error: unknown }) { if (error) return <p className="text-destructive">{errorMessage(error)}</p>; if (!data) return <p>Đang tải…</p>; return <div className="rounded-xl border bg-card p-4 text-sm text-muted-foreground">Dữ liệu đã được tải. Mở màn hình chuyên dụng để xem chi tiết vận hành.</div> }
